apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: api-health-check
  namespace: staging
spec:
  default:
    config:
      type: HTTP
      httpHealthCheck:
        port: 8080
        requestPath: /health  # 200 OK
  targetRef:
    group: ""
    kind: Service
    name: devops-test-api-devops-test-api