steps:
  # Build imagen
  - name: gcr.io/cloud-builders/docker
    dir: app
    args:
      [
        "build",
        "-t",
        "us-central1-docker.pkg.dev/$PROJECT_ID/staging-repo/devops-demo-api:$SHORT_SHA",
        "."
      ]

  # Push imagen
  - name: gcr.io/cloud-builders/docker
    args:
      [
        "push",
        "us-central1-docker.pkg.dev/$PROJECT_ID/staging-repo/devops-demo-api:$SHORT_SHA"
      ]

  # Obtener credenciales GKE
  - name: gcr.io/cloud-builders/gcloud
    args:
      [
        "container",
        "clusters",
        "get-credentials",
        "staging-cluster",
        "--region",
        "us-central1"
      ]

  # Deploy con Helm (GitOps)
  - name: alpine/helm:3.14.0
    entrypoint: sh
    args:
      - -c
      - |
        helm upgrade --install devops-test-api ../helm/devops-test-api \
          --namespace staging \
          --create-namespace \
          --set image.repository=us-central1-docker.pkg.dev/$PROJECT_ID/staging-repo/devops-demo-api \
          --set image.tag=$SHORT_SHA

images:
  - us-central1-docker.pkg.dev/$PROJECT_ID/staging-repo/devops-demo-api:$SHORT_SHA

options:
  logging: CLOUD_LOGGING_ONLY