apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: api-scaler
  namespace: staging
spec:
  scaleTargetRef:
    name: devops-test-api-devops-test-api
  minReplicaCount: 0
  maxReplicaCount: 10
  triggers:
  - type: gcp-stackdriver
    authenticationRef:               
      name: gcp-stackdriver-auth     
    metadata:
      projectId: devops-test-2026
      filter: metric.type="loadbalancing.googleapis.com/https/request_count"
      targetValue: "5"
      alignmentPeriodSeconds: "60"
      perSeriesAligner: ALIGN_RATE

## Cpu ussage removed as scaling metric in favor of GCP Stackdriver request count metric