apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: api-scaler
  namespace: prod
spec:
  scaleTargetRef:
    name: devops-test-api-devops-api
    kind: Deployment
  
  minReplicaCount: 0   
  maxReplicaCount: 10  
  pollingInterval: 30  
  cooldownPeriod: 300  

  triggers:
  - type: gcp-stackdriver
    metadata:
      projectId: devops-test-2026

      filter: 'resource.type="k8s_container" AND resource.labels.container_name="devops-test-api-devops-api" AND textPayload:"/transaction"'
  
      targetValue: "5"
    authenticationRef:
      name: gcp-stackdriver-auth

  - type: cpu
    metadata:
      type: Utilization
      value: "70" 